### ISSUE TITLE
SQL Alchemy dependencies issue

### ISSUE THREAD

**Issue by itaise** [great-expectations/airflow-provider-great-expectations#54]
Hi,
We have a dependency conflict when using the provider package. 

Starting from Airflow 2.3.3, the Airflow [constraints](https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-3.7.txt) file requires Sql Alchemy **1.4.27** while the great expectations [provider](https://github.com/great-expectations/airflow-provider-great-expectations/blob/main/setup.py#L21) requires a version earlier than **1.4.10.**

Can someone please advice? Is this requirement planned to be changed? 
Thanks a lot!

**Comment by potiuk** [comment]
Yeah. I think the limitation is because we used to have the limitation in Airlfow (the problem was that we had mssql compatibility problem), but unless there is a good reason why it's there, it's likely not needed (the problem has been solved since in sqlalchemy and removed in airflow: https://github.com/apache/airflow/commit/0853d60f16b45472ebac83bcb4fb6de112c90d6b

And unlesss there was a good reason for Great Expectations to add the limit, this upper-bound limit should not be there in the first place (it's an airlfow problem not GE problem and limit in airflow was already limiting it.

**Comment by itaise** [comment]
Thank you @potiuk! How would you recommend going about solving it? 
Should I open a PR with the upper bound removed?

**Comment by potiuk** [comment]
It's a matter of Great Expectations maintainers (I am not one of them) - but yeah, that's what I'd do :)

**Comment by itaise** [comment]
@talagluck  maybe you can advise? thanks a lot!

**Comment by eladkal** [comment]
Solved by https://github.com/great-expectations/airflow-provider-great-expectations/pull/55
@itaise we can close this issue.
Thanks @talagluck for helping quickly
